name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  deploy-to-azure:
    name: Deploy to Azure VM
    # This job runs only on pushes to the master branch, not on pull requests
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
      
      - name: Copy Nginx config to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: "scripts/nginx.conf"
          target: "/tmp/"
        
      - name: Setup Nginx configuration
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            # Ensure the destination directory exists
            sudo mkdir -p /var/www/terminal-portfolio
            
            # Setup Nginx configuration
            if [ ! -f /etc/nginx/sites-available/portfolio ] || ! cmp -s /tmp/nginx.conf /etc/nginx/sites-available/portfolio; then
              echo "Updating Nginx configuration..."
              sudo cp /tmp/nginx.conf /etc/nginx/sites-available/portfolio
              sudo ln -sf /etc/nginx/sites-available/portfolio /etc/nginx/sites-enabled/
              sudo rm -f /etc/nginx/sites-enabled/default
              
              # Test Nginx configuration
              sudo nginx -t && sudo systemctl reload nginx
            else
              echo "Nginx configuration is up to date"
            fi
      
      - name: Copy build files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: "dist/*"
          target: "/tmp/terminal-portfolio-deploy"
          strip_components: 1
      
      - name: Move files and set permissions
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            echo "Copying files to web directory..."
            sudo mkdir -p /var/www/terminal-portfolio
            sudo cp -r /tmp/terminal-portfolio-deploy/* /var/www/terminal-portfolio/
            sudo chown -R www-data:www-data /var/www/terminal-portfolio
            sudo chmod -R 755 /var/www/terminal-portfolio
            rm -rf /tmp/terminal-portfolio-deploy
            sudo systemctl reload nginx
            echo "Deployment completed successfully!"
      
      - name: Copy build files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: "dist/*"
          target: "/tmp/terminal-portfolio-deploy"
          strip_components: 1
      
      - name: Move files and set permissions
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            echo "Copying files to web directory..."
            sudo cp -r /tmp/terminal-portfolio-deploy/* /var/www/terminal-portfolio/
            sudo chown -R www-data:www-data /var/www/terminal-portfolio
            sudo chmod -R 755 /var/www/terminal-portfolio
            rm -rf /tmp/terminal-portfolio-deploy
            sudo systemctl reload nginx
            echo "Deployment completed successfully!"
